# Generated by Django 5.2.12 on 2026-03-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('trading', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
            preserve_default=False,
        ),
    ]
