# Generated by Django 5.2.12 on 2026-03-23 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('trading', '0003_trade_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('LIMIT_BUY', 'Limit Buy'), ('LIMIT_SELL', 'Limit Sell'), ('STOP_LOSS', 'Stop Loss'), ('TAKE_PROFIT', 'Take Profit')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('trigger_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='trading.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
