# Generated by Django 5.2.12 on 2026-03-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(choices=[('doji', 'Doji'), ('hammer', 'Hammer'), ('shooting_star', 'Shooting Star'), ('bullish_engulfing', 'Bullish Engulfing'), ('bearish_engulfing', 'Bearish Engulfing'), ('morning_star', 'Morning Star'), ('evening_star', 'Evening Star'), ('three_white_soldiers', 'Three White Soldiers'), ('three_black_crows', 'Three Black Crows')], max_length=40)),
                ('signal', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=10)),
                ('candle_dt', models.DateTimeField()),
                ('timeframe', models.CharField(default='1d', max_length=5)),
                ('strength', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='stocks.stock')),
            ],
            options={
                'ordering': ['-candle_dt'],
                'unique_together': {('stock', 'pattern_name', 'candle_dt', 'timeframe')},
            },
        ),
    ]
