# Generated by Django 5.2.12 on 2026-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(choices=[('doji', 'Doji'), ('hammer', 'Hammer'), ('shooting_star', 'Shooting Star'), ('bullish_engulfing', 'Bullish Engulfing'), ('bearish_engulfing', 'Bearish Engulfing'), ('morning_star', 'Morning Star'), ('evening_star', 'Evening Star'), ('three_white_soldiers', 'Three White Soldiers'), ('three_black_crows', 'Three Black Crows')], max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=60)),
                ('emoji', models.CharField(default='', max_length=10)),
                ('signal', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=10)),
                ('one_liner', models.CharField(max_length=200)),
                ('what_it_means', models.TextField()),
                ('how_to_trade', models.TextField()),
                ('reliability', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pattern Education',
                'verbose_name_plural': 'Pattern Education',
                'ordering': ['pattern_name'],
            },
        ),
    ]
