# Generated by Django 5.1.2 on 2025-04-10 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price_at_trade',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='trade_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_type',
        ),
        migrations.AddField(
            model_name='trade',
            name='action',
            field=models.CharField(default='buy', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='coin_name',
            field=models.CharField(default='bitcoin', max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default='BTCUSDT', max_length=20),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('total_quantity', models.FloatField()),
                ('average_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
