# Generated by Django 5.1.2 on 2025-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0002_rename_price_at_trade_trade_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='buy_price',
            field=models.FloatField(default=100.0),
        ),
    ]
