# Generated by Django 5.1.2 on 2025-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0003_portfolio_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
