# Generated by Django 5.1.2 on 2025-04-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0005_rename_coin_name_portfolio_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='average_price',
            new_name='current_price',
        ),
    ]
