# Generated by Django 5.1.2 on 2025-04-10 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0006_rename_average_price_portfolio_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coin_name',
            field=models.CharField(default='Bitcoin', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
