# Generated by Django 5.1.2 on 2025-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0007_remove_portfolio_coin_remove_portfolio_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='coin_name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(default='BTCUSDT', max_length=20),
        ),
    ]
