# Generated by Django 5.1.2 on 2025-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0008_remove_portfolio_coin_name_portfolio_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coin_symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
