# Generated by Django 5.1.2 on 2025-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0009_remove_portfolio_symbol_portfolio_coin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='coin_symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
