# Generated by Django 5.1.2 on 2025-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0010_alter_portfolio_coin_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='symbol',
        ),
        migrations.AddField(
            model_name='buy',
            name='coin_symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
