# Generated by Django 5.1.2 on 2025-04-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0011_remove_buy_symbol_buy_coin_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='symbol',
            new_name='coin_symbol',
        ),
    ]
