# Generated by Django 5.1.2 on 2025-04-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
