# Generated by Django 5.1.2 on 2025-04-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChartLiz', '0016_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='total_amount',
            new_name='total_value',
        ),
    ]
