# Generated by Django 5.2.12 on 2026-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='trigger_at',
            new_name='triggered_at',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('pattern', 'Pattern Detected'), ('rsi_above', 'RSI Above'), ('rsi_below', 'RSI Below'), ('macd_cross_up', 'MACD Bullish Cross'), ('macd_cross_dn', 'MACD Bearish Cross')], max_length=30),
        ),
    ]
